<?php
namespace BLMS\Tests;

use BLMS\AuthRequest;
use BLMS\BLMSRequest;
use BLMS\BLMSResponse;

use PHPUnit\Framework\TestCase as Test;

class AuthRequestTest extends Test
{
    protected $request;
    protected $cache;

    protected $config = [
        'method' => 'POST',
        'endpoint' => '/login',
        'token' => 'foo_access_token'
    ];

    protected function setUp(): void
    {
        list($method, $endpoint, $token) = array_values($this->config);
        $this->request = new BLMSRequest($method, $endpoint, $token);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAnEmptyAuthRequestEntityCanInstantiate()
    {
        $app = new AuthRequest('foo_method', 'foo_endpoint');
        $this->assertInstanceOf('BLMS\AuthRequest', $app);
    }

    public function testAuthRequestCanGetAttributes()
    {
        $auth = new AuthRequest('POST', '/login');
        $this->assertEquals('/login', $auth->getEndpoint());
        $this->assertEquals('POST', $auth->getMethod());
    }

    public function testAuthRequestCanRefreshToken()
    {
        $response = new BLMSResponse(
            $this->request,
            '{"token": {"access_token": "foo_access_token", "expires_in": 60}}',
            200
        );

        $auth = new AuthRequest('foo_method', 'foo_endpoint');
        $this->assertEquals('foo_access_token', $auth->saveTokenFromResponse($response));
    }
}
